t = '\t'

new_card = (
    t*3 + '<!-- Card: Diamond Leader Training -->\n'
    + t*3 + '<article class="ncll-card ncll-card--overlay ncll-card--volunteer ncll-card--toggle" aria-labelledby="coach-dl-title">\n'
    + t*4 + '<input type="radio" name="coach-dl" id="coach-dl-intro" checked />\n'
    + t*4 + '<input type="radio" name="coach-dl" id="coach-dl-0" />\n'
    + t*4 + '<input type="radio" name="coach-dl" id="coach-dl-1" />\n'
    + t*4 + '<input type="radio" name="coach-dl" id="coach-dl-2" />\n'
    + t*4 + '<input type="radio" name="coach-dl" id="coach-dl-3" />\n'
    + '\n'
    + t*4 + '<div class="ncll-card__sticky-heading">\n'
    + t*5 + '<div class="ncll-card__heading-title">\n'
    + t*6 + '<img class="ncll-card__sport-icon" src="https://ncllball.github.io/images/site_navigation/baseball.png" alt="Baseball icon" />\n'
    + t*6 + '<h3 class="ncll-card__title" id="coach-dl-title"><span class="text-background">Diamond Leader Training</span></h3>\n'
    + t*6 + '<img class="ncll-card__sport-icon" src="https://ncllball.github.io/images/site_navigation/baseball.png" alt="Baseball icon" />\n'
    + t*5 + '</div>\n'
    + t*4 + '</div>\n'
    + '\n'
    + t*4 + '<div class="ncll-card__body panel panel-intro">\n'
    + t*5 + '<div class="ncll-card__details">\n'
    + t*6 + '<p class="ncll-card__blurb">Real-life scenarios that help you understand your impact on players &mdash; mental, social, and emotional well-being in youth sports.</p>\n'
    + t*6 + '<div class="ncll-card__graphics">\n'
    + t*7 + '<img class="ncll-card__graphic ncll-card__graphic--large" src="https://ncllball.github.io/images/diamond-leader-course.png" alt="Diamond Leader Training course" />\n'
    + t*6 + '</div>\n'
    + t*6 + '<p class="ncll-card__blurb">Free from Little League International. Complete it once and receive a certificate valid for tournament coaching eligibility &mdash; strongly encouraged for all coaches.</p>\n'
    + t*5 + '</div>\n'
    + t*4 + '</div>\n'
    + '\n'
    + t*4 + '<div class="ncll-card__body panel panel0">\n'
    + t*5 + '<div class="ncll-card__details">\n'
    + t*6 + '<h4 class="left">Details</h4>\n'
    + t*6 + '<ul class="ncll-card__meta">\n'
    + t*7 + '<li><strong>Time:</strong> Self-paced</li>\n'
    + t*7 + '<li><strong>Cost:</strong> Free</li>\n'
    + t*7 + '<li><strong>Frequency:</strong> One-time &mdash; certificate does not expire</li>\n'
    + t*7 + '<li><strong>Deadline:</strong> Before your first tournament game</li>\n'
    + t*7 + '<li><strong>Proof:</strong> Certificate issued upon completion</li>\n'
    + t*7 + '<li><strong>Required for:</strong> Tournament managers and coaches (required); all coaches (strongly encouraged)</li>\n'
    + t*6 + '</ul>\n'
    + t*5 + '</div>\n'
    + t*4 + '</div>\n'
    + '\n'
    + t*4 + '<div class="ncll-card__body panel panel1">\n'
    + t*5 + '<div class="ncll-card__details">\n'
    + t*6 + '<h4 class="left">How to Complete</h4>\n'
    + t*6 + '<ol class="training-steps">\n'
    + t*7 + '<li>\n'
    + t*8 + '<strong>Access the Platform</strong>\n'
    + t*8 + '<ul>\n'
    + t*9 + '<li>Go to <a class="ncll" href="https://www.littleleague.org/university/articles/diamond-leader-training-program/" target="_blank" rel="noopener">Little League University &ndash; Diamond Leader Training Program</a></li>\n'
    + t*9 + '<li>Create an account (first-time) or log in (returning)</li>\n'
    + t*8 + '</ul>\n'
    + t*7 + '</li>\n'
    + t*7 + '<li>\n'
    + t*8 + '<strong>Enroll</strong>\n'
    + t*8 + '<ul>\n'
    + t*9 + '<li>Search for &ldquo;Diamond Leader Training Program&rdquo; if not immediately visible</li>\n'
    + t*9 + '<li>If asked, search for North Central Little League</li>\n'
    + t*9 + '<li>Open the course and click Enroll / Register</li>\n'
    + t*8 + '</ul>\n'
    + t*7 + '</li>\n'
    + t*7 + '<li>\n'
    + t*8 + '<strong>Complete Modules</strong>\n'
    + t*8 + '<ul>\n'
    + t*9 + '<li>Work through the real-life scenario modules at your own pace</li>\n'
    + t*9 + '<li>Review the supporting resources in each section</li>\n'
    + t*8 + '</ul>\n'
    + t*7 + '</li>\n'
    + t*7 + '<li>\n'
    + t*8 + '<strong>Receive Your Certificate</strong>\n'
    + t*8 + '<ul>\n'
    + t*9 + '<li>A certificate is issued upon completion &mdash; save or print for your records</li>\n'
    + t*9 + '<li>Certificate is valid for tournament coaching eligibility</li>\n'
    + t*8 + '</ul>\n'
    + t*7 + '</li>\n'
    + t*6 + '</ol>\n'
    + t*5 + '</div>\n'
    + t*4 + '</div>\n'
    + '\n'
    + t*4 + '<div class="ncll-card__body panel panel2">\n'
    + t*5 + '<div class="ncll-card__details">\n'
    + t*6 + '<h4 class="left">Tips &amp; Reminders</h4>\n'
    + t*6 + '<ul>\n'
    + t*7 + '<li><strong>One-time only:</strong> Unlike Abuse Awareness, you do not need to retake this course each year</li>\n'
    + t*7 + '<li><strong>Revisit anytime:</strong> LLI strongly encourages returning to review content and resources throughout your coaching career</li>\n'
    + t*7 + '<li><strong>Tournament requirement:</strong> Required for tournament coaching eligibility &mdash; complete before your first tournament game</li>\n'
    + t*7 + '<li><strong>Strongly encouraged for all coaches:</strong> Even if you&rsquo;re not coaching tournaments, the content applies to every practice and game</li>\n'
    + t*7 + '<li><strong>Technical issues:</strong> Use the LLU Help / Support link, or try a fresh browser tab or incognito mode</li>\n'
    + t*6 + '</ul>\n'
    + t*5 + '</div>\n'
    + t*4 + '</div>\n'
    + '\n'
    + t*4 + '<div class="ncll-card__body panel panel3">\n'
    + t*5 + '<div class="ncll-card__details">\n'
    + t*6 + '<h4 class="left">Get Started</h4>\n'
    + t*6 + '<p>Complete this free, self-paced course from Little League International to strengthen your coaching skills and satisfy tournament eligibility requirements.</p>\n'
    + t*6 + '<div class="ncll-card__cta">\n'
    + t*7 + '<a class="button button--primary" href="https://www.littleleague.org/university/articles/diamond-leader-training-program/" target="_blank" rel="noopener noreferrer">Start Diamond Leader Training</a>\n'
    + t*6 + '</div>\n'
    + t*6 + '<p>Questions? Email <a class="ncll" href="mailto:safety@ncllball.com">safety&#64;ncllball.com</a>.</p>\n'
    + t*6 + '<div class="ncll-card__cta">\n'
    + t*7 + '<a class="button button--primary" href="mailto:safety@ncllball.com?subject=Diamond%20Leader%20Training%20Question">Contact Safety Officer</a>\n'
    + t*6 + '</div>\n'
    + t*5 + '</div>\n'
    + t*4 + '</div>\n'
    + '\n'
    + t*4 + '<div class="ncll-card__sticky-footer">\n'
    + t*5 + '<div class="actions" role="group" aria-label="Diamond Leader card controls">\n'
    + t*6 + '<label class="button button--secondary btn-prev btn-prev-start" for="coach-dl-3">Back</label>\n'
    + t*6 + '<label class="button button--primary btn-next btn-next-intro" for="coach-dl-0">Next</label>\n'
    + t*6 + '<label class="button button--secondary btn-prev btn-prev-0" for="coach-dl-intro">Back</label>\n'
    + t*6 + '<label class="button button--primary btn-next btn-next-0" for="coach-dl-1">Next</label>\n'
    + t*6 + '<label class="button button--secondary btn-prev btn-prev-1" for="coach-dl-0">Back</label>\n'
    + t*6 + '<label class="button button--primary btn-next btn-next-1" for="coach-dl-2">Next</label>\n'
    + t*6 + '<label class="button button--secondary btn-prev btn-prev-2" for="coach-dl-1">Back</label>\n'
    + t*6 + '<label class="button button--primary btn-next btn-next-2" for="coach-dl-3">Next</label>\n'
    + t*6 + '<label class="button button--secondary btn-prev btn-prev-3" for="coach-dl-2">Back</label>\n'
    + t*6 + '<label class="button button--primary btn-next btn-next-3" for="coach-dl-intro">Start Over</label>\n'
    + t*5 + '</div>\n'
    + t*4 + '</div>\n'
    + t*3 + '</article>'
)

with open('c:/Tools/ncllball.github.io/Resources/coaches-hub.html', 'r', encoding='utf-8') as f:
    content = f.read()

start_marker = '\t\t\t<!-- Card: Diamond Leader Training -->'
end_marker = '\t\t\t</article>'

start_idx = content.find(start_marker)
end_idx = content.find(end_marker, start_idx) + len(end_marker)

print(f"Start: {start_idx}, End: {end_idx}")
print("Snippet before:", repr(content[end_idx-30:end_idx+20]))

new_content = content[:start_idx] + new_card + content[end_idx:]

with open('c:/Tools/ncllball.github.io/Resources/coaches-hub.html', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Done.")
